# The URL the site will be built for
base_url = "https://dehamzah.com"

title = "Dede Hamzah"
description = "Software engineer passionate about building tools, platforms, and systems at scale. I work across the stack with Typescript and Cloud Infrastructure."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anemone"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
list_blog = true
show_open_source = true
toc = true
display_author = true
header_nav = [
  { url = "/", name_en = "/home" },
  { url = "/blog", name_en = "/blog" },
  { url = "/about", name_en = "/about" },
]

